name : Android CI
on:
 push:
   branches: [main]
 pull_request:
    branches: [main]
jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup JDK
          uses: actions/setup-java@v2.1.0
          with:
           java-version: 16.0.1
           architecture: x64
           distribution: adopt
           check-latest: true
           java-package: jdk
           server-id: github
           server-username: GITHUB_ACTOR
           server-password: GITHUB_TOKEN
           overwrite-settings: true
        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        - name: Build the weighpad app
          run: cd ap_weighpad_lcs && chmod +x ./gradlew && ./gradlew build
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.2.4
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
